[package]
name = "rd"
version = "0.0.0"
authors = ["Sidharth Kshatriya"]
edition = "2018"
build = "build.rs"

[dependencies]
array-init = "0.1.1"
brotli-sys = "0.3.2"
capnp = "0.12"
gimli = "0.21.0"
goblin = "0.2"
backtrace = "0.3.48"
bitflags = "1.2.1"
lazy_static = "1.4.0"
libc = "0.2.70"
memchr = "2.3.3"
memoffset = "0.5.4"
nix = "0.17"
rand = "0.7"
raw-cpuid = "7.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1.1.0"
structopt = "0.3"

[build-dependencies]
bindgen = "0.53.2"
capnpc = "0.12"

[features]
default = []
verify_syscall_numbers = []
