[package]
name = "rd"
version = "0.1.0"
authors = ["Sidharth Kshatriya"]
edition = "2018"
build = "build.rs"

[dependencies]
array-init = "0.1.1"
capnp = "0.12.1"
# gimli = "0.20.0"
# goblin = "0.1.3"
backtrace = "0.3.46"
bitflags = "1.2.1"
lazy_static = "1.4.0"
libc = "0.2.68"
memchr = "2.3.3"
nix = "0.17"
raw-cpuid = "7.0.3"
static_assertions = "1.1.0"
structopt = "0.3.12"

[build-dependencies]
bindgen = "0.53.2"
capnpc = "0.12"

[features]
default = []
verify_syscall_numbers = []