[package]
name = "rd"
version = "0.1.0"
authors = ["Sidharth Kshatriya"]
edition = "2018"
build = "build.rs"

[dependencies]
# capnp = "0.11.1"
# gimli = "0.20.0"
# goblin = "0.1.3"
libc = "0.2.66"
nix = "0.16.1"
structopt = "0.3.7"

[build-dependencies]
bindgen = "0.52.0"
